// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'question_model_v2.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_QuestionModelV2 _$QuestionModelV2FromJson(
  Map<String, dynamic> json,
) => _QuestionModelV2(
  questionId: (json['questionId'] as num?)?.toInt() ?? 0,
  sourceId: (json['sourceId'] as num?)?.toInt(),
  readingId: (json['readingId'] as num?)?.toInt(),
  order: (json['order'] as num?)?.toInt() ?? 0,
  questionText: json['questionText'] as String? ?? '',
  questionTextLatex: json['questionTextLatex'] as String? ?? '',
  solutionText: json['solutionText'] as String? ?? '',
  solutionTextLatex: json['solutionTextLatex'] as String? ?? '',
  readingTitle: json['readingTitle'] as String? ?? '',
  readingText: json['readingText'] as String? ?? '',
  readingTextVn: json['readingTextVn'] as String? ?? '',
  llmSolutionText: json['llmSolutionText'] as String?,
  llmSolutionTextLatex: json['llmSolutionTextLatex'] as String?,
  llmSolutionConfidenceScore: (json['llmSolutionConfidenceScore'] as num?)
      ?.toDouble(),
  readingTextLatex: json['readingTextLatex'] as String?,
  imageDescription: json['imageDescription'] as String?,
  answerKey: json['answerKey'] as String?,
  correctAnswer: json['correctAnswer'] as String?,
  answerDataFormatCode: json['answerDataFormatCode'] as String?,
  originalLanguageCode: json['originalLanguageCode'] as String?,
  classId: (json['classId'] as num?)?.toInt(),
  className: json['className'] as String?,
  subjectId: (json['subjectId'] as num?)?.toInt(),
  subjectName: json['subjectName'] as String?,
  chapterId: (json['chapterId'] as num?)?.toInt(),
  chapterName: json['chapterName'] as String?,
  topicId: (json['topicId'] as num?)?.toInt(),
  topicName: json['topicName'] as String?,
  objectiveId: (json['objectiveId'] as num?)?.toInt(),
  objectiveName: json['objectiveName'] as String?,
  insightId: (json['insightId'] as num?)?.toInt(),
  insightName: json['insightName'] as String?,
  abilityId: (json['abilityId'] as num?)?.toInt(),
  abilityName: json['abilityName'] as String?,
  abilityTwoId: (json['abilityTwoId'] as num?)?.toInt(),
  abilityTwoName: json['abilityTwoName'] as String?,
  cognitiveId: (json['cognitiveId'] as num?)?.toInt(),
  cognitiveName: json['cognitiveName'] as String?,
  cognitiveTwoId: (json['cognitiveTwoId'] as num?)?.toInt(),
  cognitiveTwoName: json['cognitiveTwoName'] as String?,
  knowledgeId: (json['knowledgeId'] as num?)?.toInt(),
  knowledgeName: json['knowledgeName'] as String?,
  knowledgeTwoId: (json['knowledgeTwoId'] as num?)?.toInt(),
  knowledgeTwoName: json['knowledgeTwoName'] as String?,
  difficultyId: (json['difficultyId'] as num?)?.toInt(),
  difficultyName: json['difficultyName'] as String?,
  difficultyTwoId: (json['difficultyTwoId'] as num?)?.toInt(),
  difficultyTwoName: json['difficultyTwoName'] as String?,
  levelId: (json['levelId'] as num?)?.toInt(),
  levelName: json['levelName'] as String?,
  questionTypeId: (json['questionTypeId'] as num?)?.toInt(),
  hasError: json['hasError'] as bool?,
  reviewStatus: json['reviewStatus'] as String?,
  reviewUpdatedAt: json['reviewUpdatedAt'] == null
      ? null
      : DateTime.parse(json['reviewUpdatedAt'] as String),
  reviewUpdatedBy: json['reviewUpdatedBy'] as String?,
  llmSyncedAt: json['llmSyncedAt'] == null
      ? null
      : DateTime.parse(json['llmSyncedAt'] as String),
  importSyncedAt: json['importSyncedAt'] == null
      ? null
      : DateTime.parse(json['importSyncedAt'] as String),
  issueTypeCode: json['issueTypeCode'] as String?,
  issueSeverityCode: json['issueSeverityCode'] as String?,
  issueText: json['issueText'] as String?,
  suggestedFixText: json['suggestedFixText'] as String?,
  issueUpdatedAt: json['issueUpdatedAt'] == null
      ? null
      : DateTime.parse(json['issueUpdatedAt'] as String),
  createdAt: json['createdAt'] == null
      ? null
      : DateTime.parse(json['createdAt'] as String),
  updatedAt: json['updatedAt'] == null
      ? null
      : DateTime.parse(json['updatedAt'] as String),
  classConfidenceScore: (json['classConfidenceScore'] as num?)?.toDouble(),
  subjectConfidenceScore: (json['subjectConfidenceScore'] as num?)?.toDouble(),
  chapterConfidenceScore: (json['chapterConfidenceScore'] as num?)?.toDouble(),
  topicConfidenceScore: (json['topicConfidenceScore'] as num?)?.toDouble(),
  objectiveConfidenceScore: (json['objectiveConfidenceScore'] as num?)
      ?.toDouble(),
  insightConfidenceScore: (json['insightConfidenceScore'] as num?)?.toDouble(),
  abilityConfidenceScore: (json['abilityConfidenceScore'] as num?)?.toDouble(),
  cognitiveConfidenceScore: (json['cognitiveConfidenceScore'] as num?)
      ?.toDouble(),
  knowledgeConfidenceScore: (json['knowledgeConfidenceScore'] as num?)
      ?.toDouble(),
  difficultyConfidenceScore: (json['difficultyConfidenceScore'] as num?)
      ?.toDouble(),
  isImported: json['isImported'] as bool? ?? false,
  isDelete: json['isDelete'] as bool? ?? false,
  options:
      (json['options'] as List<dynamic>?)
          ?.map((e) => OptionModel.fromJson(e as Map<String, dynamic>))
          .toList() ??
      const [],
);

Map<String, dynamic> _$QuestionModelV2ToJson(_QuestionModelV2 instance) =>
    <String, dynamic>{
      'questionId': instance.questionId,
      'sourceId': instance.sourceId,
      'readingId': instance.readingId,
      'order': instance.order,
      'questionText': instance.questionText,
      'questionTextLatex': instance.questionTextLatex,
      'solutionText': instance.solutionText,
      'solutionTextLatex': instance.solutionTextLatex,
      'readingTitle': instance.readingTitle,
      'readingText': instance.readingText,
      'readingTextVn': instance.readingTextVn,
      'llmSolutionText': instance.llmSolutionText,
      'llmSolutionTextLatex': instance.llmSolutionTextLatex,
      'llmSolutionConfidenceScore': instance.llmSolutionConfidenceScore,
      'readingTextLatex': instance.readingTextLatex,
      'imageDescription': instance.imageDescription,
      'answerKey': instance.answerKey,
      'correctAnswer': instance.correctAnswer,
      'answerDataFormatCode': instance.answerDataFormatCode,
      'originalLanguageCode': instance.originalLanguageCode,
      'classId': instance.classId,
      'className': instance.className,
      'subjectId': instance.subjectId,
      'subjectName': instance.subjectName,
      'chapterId': instance.chapterId,
      'chapterName': instance.chapterName,
      'topicId': instance.topicId,
      'topicName': instance.topicName,
      'objectiveId': instance.objectiveId,
      'objectiveName': instance.objectiveName,
      'insightId': instance.insightId,
      'insightName': instance.insightName,
      'abilityId': instance.abilityId,
      'abilityName': instance.abilityName,
      'abilityTwoId': instance.abilityTwoId,
      'abilityTwoName': instance.abilityTwoName,
      'cognitiveId': instance.cognitiveId,
      'cognitiveName': instance.cognitiveName,
      'cognitiveTwoId': instance.cognitiveTwoId,
      'cognitiveTwoName': instance.cognitiveTwoName,
      'knowledgeId': instance.knowledgeId,
      'knowledgeName': instance.knowledgeName,
      'knowledgeTwoId': instance.knowledgeTwoId,
      'knowledgeTwoName': instance.knowledgeTwoName,
      'difficultyId': instance.difficultyId,
      'difficultyName': instance.difficultyName,
      'difficultyTwoId': instance.difficultyTwoId,
      'difficultyTwoName': instance.difficultyTwoName,
      'levelId': instance.levelId,
      'levelName': instance.levelName,
      'questionTypeId': instance.questionTypeId,
      'hasError': instance.hasError,
      'reviewStatus': instance.reviewStatus,
      'reviewUpdatedAt': instance.reviewUpdatedAt?.toIso8601String(),
      'reviewUpdatedBy': instance.reviewUpdatedBy,
      'llmSyncedAt': instance.llmSyncedAt?.toIso8601String(),
      'importSyncedAt': instance.importSyncedAt?.toIso8601String(),
      'issueTypeCode': instance.issueTypeCode,
      'issueSeverityCode': instance.issueSeverityCode,
      'issueText': instance.issueText,
      'suggestedFixText': instance.suggestedFixText,
      'issueUpdatedAt': instance.issueUpdatedAt?.toIso8601String(),
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'classConfidenceScore': instance.classConfidenceScore,
      'subjectConfidenceScore': instance.subjectConfidenceScore,
      'chapterConfidenceScore': instance.chapterConfidenceScore,
      'topicConfidenceScore': instance.topicConfidenceScore,
      'objectiveConfidenceScore': instance.objectiveConfidenceScore,
      'insightConfidenceScore': instance.insightConfidenceScore,
      'abilityConfidenceScore': instance.abilityConfidenceScore,
      'cognitiveConfidenceScore': instance.cognitiveConfidenceScore,
      'knowledgeConfidenceScore': instance.knowledgeConfidenceScore,
      'difficultyConfidenceScore': instance.difficultyConfidenceScore,
      'isImported': instance.isImported,
      'isDelete': instance.isDelete,
      'options': instance.options,
    };
